### PR TITLE
Fix binary ops RHS in pattern matching switch

### LINKED ISSUE #573: <? Operator behaves weirdly while pattern matching
```ts
switch value
 <? "string"
  value
 []
  value.map(&.toString())
 true
  value

// ↓↓↓ Civet 0.6.11
if (value instanceof "string") {
  return value;
} else if (Array.isArray(value) && value.length === 0) {
  return value.map(($) => $.toString());
} else if (value === true) {
  return value;
}

```

### PR DESCRIPTION
**Pull request by edemaine**
Fixes #573

### CODE REVIEW

File: source/lib.js [hunk 1]
```diff
@@ -832,13 +832,13 @@ function expandChainedComparisons([first, binops]) {
...
 
-        results = results.concat(first, ...binops.slice(start, endIndex))
+        results.push(first, ...binops.slice(start, endIndex).flat())
         first = [exp].concat(binops.slice(index + 1, endIndex))
         start = endIndex
       })
     } else {
       // Advance start if there was no chain
-      results = results.concat(first, ...binops.slice(start, i + 1))
+      results.push(first, ...binops.slice(start, i + 1).flat())
```
Comment (edemaine) [inline source/lib.js:841]: These changes from `concat` to `push` turned out to not be necessary, but they would be if `first` were even an array (so that it gets treated like a single thing). I left the change in also because it should be faster to be in-place.

**Review by STRd6 — APPROVED** [review]
Looks good, thanks!
